Lavalink
binaryoverload/FlareBot-Selfhosting pull request #1
Opened 2018-07-14 16:08 UTC by weeryan17

Implemented everything lavalink

Mover over to our own system for handling music (don't know if we should remove lavaplayer bridge yet)
Implemented Lavalink node support

Not much else to say

2018-07-14 16:09 UTC, weeryan17 commented
Also first self host edition pr hype!!!!

2018-07-14 18:57 UTC, binaryoverload requested changes

2018-07-14 18:57 UTC, binaryoverload commented on config.example.yml
> +# defines your lavalink nodes
Capital? Maybe?

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Client.java
> +        /*musicManager.getPlayerCreateHooks()
Why do we have commented code 🤔

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Client.java
> +            players.put(guildId, createPlayer(guildId));
Use getOrDefault instead

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Client.java
> +            tracks.put(guildId, new ArrayList<>());
same here

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Config.java
> +    private String souldcloudApi;
`soundCloudApi`*

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Config.java
> +                    /*log.error("Sound cloud is enabled but no client id is present!");
Meant to be commented?

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Config.java
> +        return souldcloudApi;
Commented?

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Events.java
> +        /*if (event.getMember().getUser().equals(event.getJDA().getSelfUser()) && Client.instance().getMusicManager()
Commented? Can we add reasons for commented code please

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Getters.java
> +    /*public static int getSongsQueued() {
👀

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/audio/PlayerListener.java
> +/*
Why is this commented? Delete the file 👀

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/KillCommand.java
> +        /*if (guild.getGuild().getAudioManager().isAttemptingToConnect() || guild.getGuild().getAudioManager().isConnected()) {
Don't comment out code to disable, return and comment

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/LoopCommand.java
> +        /*Player player = Client.instance().getMusicManager().getPlayer(channel.getGuild().getId());
Same, also why are disabling commands?

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/RepeatCommand.java
> +        /*Player player = Client.instance().getMusicManager().getPlayer(channel.getGuild().getId());
See previous

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/music/VideoThread.java
> +            //SourceProvider provider = getProviderFromURL(url);
Commented? If you're gonna comment out code comment a reason

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/music/VideoThread.java
> +        /*try {
Commentedddd

2018-07-14 18:57 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/util/general/GuildUtils.java
> +            /*musicManager.getPlayer(channel.getGuild().getId()).play();
Again

2018-07-14 22:44 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Client.java
> +        /*musicManager.getPlayerCreateHooks()
Me testing stuff and not wating to remove it in case i broke something

2018-07-14 22:45 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Config.java
> +                    /*log.error("Sound cloud is enabled but no client id is present!");
Yes because soundcloud won't let you generate apps atm

2018-07-14 22:45 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Config.java
> +    private String souldcloudApi;
soundcloud is all lowercase

2018-07-14 22:46 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/LoopCommand.java
> +        /*Player player = Client.instance().getMusicManager().getPlayer(channel.getGuild().getId());
because currently they'd be a pian to implement so I'll work on implementing them later

2018-07-14 22:47 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Config.java
> +                    /*log.error("Sound cloud is enabled but no client id is present!");
And I don't want to delete the code because i want to use their api when it actually becomes available again

2018-07-14 22:53 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Client.java
> +            players.put(guildId, createPlayer(guildId));
getOrDefault likes to return null and i have no clue why. doing it this way actually returns something

2018-07-15 23:46 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Config.java
> +        return souldcloudApi;
above

2018-07-16 06:46 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Client.java
> +            players.put(guildId, createPlayer(guildId));
Testing to prove this, 99.9% sure it won't return null if the default is not null

2018-07-16 06:47 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Config.java
> +    private String souldcloudApi;
Well at least spell it right then :P

2018-07-16 06:47 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/Config.java
> +        return souldcloudApi;
?? That doesn't explain why this is commented

2018-07-16 06:55 UTC, binaryoverload requested changes

2018-07-16 06:55 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/SearchCommand.java
> +    public static boolean joinChannel(GuildWrapper guild, TextChannel channel, Member member) {
This shouldn't be in a command file, is there a utils file you can put this in?

2018-07-16 06:55 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/SkipCommand.java
> +    private void skip(String guildId) {
A custom implementation of a player should be make for all these

2018-07-16 06:55 UTC, binaryoverload commented on src/main/java/stream/flarebot/flarebot/util/SourceProvider.java
> +    YOUTUBE(VideoThread.YOUTUBE_PATTERN),
Do the patterns need to be in `VideoThread`?

2018-07-16 13:59 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/Client.java
> +            players.put(guildId, createPlayer(guildId));
I already did test. I had getOrDefault in early stages of testing and it kept returning null when i first called it

2018-07-16 14:00 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/SearchCommand.java
> +    public static boolean joinChannel(GuildWrapper guild, TextChannel channel, Member member) {
that was intellij yelling at me. I'll prob make a music utils class

2018-07-16 14:01 UTC, binaryoverload commented
Well that was most likely due to "createPlayer" returning null,
getOrDefault literally does the same logic here just in a more concise way

On Mon, Jul 16, 2018 at 2:59 PM weeryan17 <notifications@github.com> wrote:

> *@weeryan17* commented on this pull request.
> ------------------------------
>
> In src/main/java/stream/flarebot/flarebot/Client.java
> <https://github.com/binaryoverload/FlareBot-Selfhosting/pull/1#discussion_r202692377>
> :
>
> > @@ -129,8 +166,36 @@ public ShardManager getShardManager() {
>          return shardManager;
>      }
>
> -    public PlayerManager getMusicManager() {
> -        return musicManager;
> +    public IPlayer getPlayer(String guildId) {
> +        if(!players.containsKey(guildId)) {
> +            players.put(guildId, createPlayer(guildId));
>
> I already did test. I had getOrDefault in early stages of testing and it
> kept returning null when i first called it
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/binaryoverload/FlareBot-Selfhosting/pull/1#discussion_r202692377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOnti7abqyzW21FI2fAyTLsodgclTDpnks5uHJxDgaJpZM4VP6Ad>
> .
>

2018-07-16 14:05 UTC, binaryoverload commented
`return (e = getNode(hash(key), key)) == null ? defaultValue :
e.value;` So either `createPlayer` was returning null or you were
testing wrong :thinking:


On Mon, Jul 16, 2018 at 3:01 PM William Oldham <wegg7250@gmail.com> wrote:

> Well that was most likely due to "createPlayer" returning null,
> getOrDefault literally does the same logic here just in a more concise way
>
> On Mon, Jul 16, 2018 at 2:59 PM weeryan17 <notifications@github.com>
> wrote:
>
>> *@weeryan17* commented on this pull request.
>> ------------------------------
>>
>> In src/main/java/stream/flarebot/flarebot/Client.java
>> <https://github.com/binaryoverload/FlareBot-Selfhosting/pull/1#discussion_r202692377>
>> :
>>
>> > @@ -129,8 +166,36 @@ public ShardManager getShardManager() {
>>          return shardManager;
>>      }
>>
>> -    public PlayerManager getMusicManager() {
>> -        return musicManager;
>> +    public IPlayer getPlayer(String guildId) {
>> +        if(!players.containsKey(guildId)) {
>> +            players.put(guildId, createPlayer(guildId));
>>
>> I already did test. I had getOrDefault in early stages of testing and it
>> kept returning null when i first called it
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/binaryoverload/FlareBot-Selfhosting/pull/1#discussion_r202692377>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AOnti7abqyzW21FI2fAyTLsodgclTDpnks5uHJxDgaJpZM4VP6Ad>
>> .
>>
>

2018-07-16 14:08 UTC, weeryan17 commented
Nope createPlayer doesn't return null unless something major went wrong. If createPlayer did return null I'd still be in a situation where i was getting npe for the getPlayer code

2018-07-16 14:11 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/commands/commands/music/SkipCommand.java
> +    private void skip(String guildId) {
I'll move it over to the new music utils. making a custom player implementation is on my todo list but thats going to be a lot of pulling my hair out that I didn't want to do till i have a good idea of how I'm going to do everything

2018-07-16 14:13 UTC, weeryan17 commented on src/main/java/stream/flarebot/flarebot/util/SourceProvider.java
> +    YOUTUBE(VideoThread.YOUTUBE_PATTERN),
nope just a convenient place to put them

2018-07-18 16:49 UTC, binaryoverload approved these changes

2018-07-18 16:50 UTC, binaryoverload commented
@weeryan17 Please do a final test then you're clear to merge ✔️

2018-07-18 16:51 UTC, weeryan17 commented
ok. btw can you make a program to convert playlists. then new system uses urls the old used ids

2018-07-18 16:52 UTC, binaryoverload commented
If will soon, if you want it done soon you'll have to :P

2018-07-18 17:36 UTC, merged